python main_mobile.py --edge_update_frequency 1 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_client_direct --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1


# only 1 epoch, all clients, frequency = 1
# python main_mobile.py --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 150 --num_epochs 1 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 1
# python main_mobile.py --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 5 epoch, all clients, frequency = 1
# python main_mobile.py --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, 0.25 clients, frequency = 1
# python main_mobile.py --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, 0.5 clients, frequency = 1
python main_mobile.py --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 3
python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6
python main_mobile.py --edge_update_frequency 6 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 9
python main_mobile.py --edge_update_frequency 9 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 12
python main_mobile.py --edge_update_frequency 12 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = 0
python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 0 --std_velocity 0  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = random
python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 0 --std_velocity 0  --sample active --model mlp --algorithm rand_fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = 100
python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 100 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = 200
python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 200 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = 50, num_edges = 10
# python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --num_edges 10 --non_iid_classes 0 --mean_velocity 100 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# 3 epoch, all clients, frequency = 6, speed = 50, num_edges = 20
# python main_mobile.py --edge_update_frequency 3 --task  mnist_cnum60_dist0_skew0_seed0 --num_edges 20 --non_iid_classes 0 --mean_velocity 100 --std_velocity 10  --sample active --model mlp --algorithm fed_edgeavg --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id -1 --num_threads 1
# python main_mobile.py --edge_update_frequency 1 --task  mnist_cnum60_dist0_skew0_seed0 --non_iid_classes 0 --mean_velocity 50 --std_velocity 10  --sample active --model mlp --algorithm fed_client_direct --num_edges 5 --num_clients 50 --std_num_clients 10 --num_rounds 100 --num_epochs 3 --learning_rate 0.001 --momentum 0.9 --proportion 1 --batch_size 10 --eval_interval 1 --gpu 0 --server_gpu_id 0 --num_threads 1
