# Non-iid experiments
# Tune alpha and temperature
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 3 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 5 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 10 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.15 --distill_temperature 5 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 0.25 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.1 --distill_temperature 20 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_distill_global --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
