# Non-iid experiments
# Clientdirect
# EdgeAvg, frequency = 3
python main_mobile.py --edge_update_frequency 3 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 9
python main_mobile.py --edge_update_frequency 9 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 2
# python main_mobile.py --edge_update_frequency 2 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6, velocity = 0 (static)
python main_mobile.py --edge_update_frequency 6  --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 0 --std_velocity 0  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6, random coordinates
# python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 0 --std_velocity 0  --sample uniform --model cnn --algorithm rand_fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6, velocity = 100
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 50 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6, velocity = 200
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 10 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 6, velocity = 10
python main_mobile.py --edge_update_frequency 6 --distill_alpha 0.2 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
# EdgeAvg, frequency = 1
python main_mobile.py --task  cifar10_cnum100_dist2_skew0.1_seed0  --distill_alpha 0.2 --mean_velocity 100 --std_velocity 5  --sample uniform --model cnn --algorithm fed_mobile_distill --num_edges 10 --num_clients 90 --std_num_clients 10 --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --momentum 0.9 --proportion 0.5 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1
