# Non-iid experiments
python main_mobile.py --edge_update_frequency 6 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
# Clientdirect
python main_mobile.py --edge_update_frequency 3 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
python main_mobile.py --edge_update_frequency 9 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
python main_mobile.py --edge_update_frequency 6 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 0 --std_velocity 0  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
python main_mobile.py --edge_update_frequency 6 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 50 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
python main_mobile.py --edge_update_frequency 6 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 100 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1
python main_mobile.py --edge_update_frequency 1 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model resnet9 --algorithm moon --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 1 --num_threads 1


python main_mobile.py --distill_alpha 0.2 --distill_global_beta 0.8 --temperature 1 --edge_model_buffer_size 10 --temperature--edge_update_frequency 6 --task  cifar10_cnum100_dist2_skew0.1_seed0  --mean_velocity 25 --std_velocity 2  --sample uniform --model resnet9 --algorithm fed_ntd --num_edges 5 --num_clients 97 --std_num_clients 3 --num_rounds 500 --num_epochs 5 --learning_rate 0.0001 --momentum 0.9  --weight_decay 1e-4 --proportion 0.25 --batch_size 64 --eval_interval 1 --gpu 0 --server_gpu_id 3 --num_threads 1

